// DELETE THIS FILE when the backend is wired up.
// In useCommunitySharing.js: change useState(SAMPLE_REQUESTS/SAMPLE_DONATIONS) → useState([])

export const SAMPLE_REQUESTS = [
  {
    _id: "req001",
    requesterName: "Kenneth Bulan",
    requesterEmail: "kenneth.bulan@email.com",
    barangay: "Dela Paz",
    address: "123 Sampaguita St., Dela Paz",
    category: "food",
    itemDescription: "Rice 5kg sack",
    quantity: 2,
    unit: "sacks",
    reason: "Lost all food supply during flooding",
    status: "pending",
    householdFlag: true,
    actionLog: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    _id: "req002",
    requesterName: "Maria Santos",
    requesterEmail: "maria.santos@email.com",
    barangay: "San Roque",
    address: "45 Rizal Ave., San Roque",
    category: "water",
    itemDescription: "Bottled water 1L",
    quantity: 24,
    unit: "bottles",
    reason: "Water supply contaminated",
    status: "pending",
    householdFlag: false,
    actionLog: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    _id: "req003",
    requesterName: "Juan Dela Cruz",
    requesterEmail: "juan.delacruz@email.com",
    barangay: "Mayamot",
    address: "78 Mabini St., Mayamot",
    category: "clothing",
    itemDescription: "Adult clothing assorted sizes",
    quantity: 5,
    unit: "sets",
    reason: "Clothes swept away by flood",
    status: "approved",
    householdFlag: false,
    actionLog: [
      { action: "approved", by: "Admin Rafael", note: "Verified with barangay captain", at: new Date(Date.now() - 1000 * 60 * 20).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    _id: "req004",
    requesterName: "Ana Reyes",
    requesterEmail: "ana.reyes@email.com",
    barangay: "Bagong Nayon",
    address: "12 Maliksi St., Bagong Nayon",
    category: "medicine",
    itemDescription: "First aid kit",
    quantity: 1,
    unit: "kit",
    reason: "Needed for elderly family member",
    status: "fulfilled",
    householdFlag: false,
    actionLog: [
      { action: "approved", by: "Admin Rafael", note: "", at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString() },
      { action: "fulfilled", by: "Admin Rafael", note: "Delivered by barangay tanod", at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    _id: "req005",
    requesterName: "Roberto Tan",
    requesterEmail: "roberto.tan@email.com",
    barangay: "Cupang",
    address: "99 Aguinaldo St., Cupang",
    category: "shelter",
    itemDescription: "Tarpaulin 8x10ft",
    quantity: 2,
    unit: "pcs",
    reason: "Roof damaged",
    status: "rejected",
    householdFlag: false,
    actionLog: [
      { action: "rejected", by: "Admin Rafael", note: "Insufficient stock — refer to DSWD for tarpaulin assistance", at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
  },
  {
    _id: "req006",
    requesterName: "Lisa Garcia",
    requesterEmail: "lisa.garcia@email.com",
    barangay: "Mambugan",
    address: "34 Kalayaan St., Mambugan",
    category: "hygiene",
    itemDescription: "Hygiene kit (soap, toothbrush, shampoo)",
    quantity: 3,
    unit: "kits",
    reason: "",
    status: "cancelled",
    householdFlag: false,
    actionLog: [
      { action: "cancelled", by: "Admin Rafael", note: "Requester picked up from relief center instead", at: new Date(Date.now() - 1000 * 60 * 45).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
  },
];

export const SAMPLE_DONATIONS = [
  {
    _id: "don001",
    donorName: "Pedro Cruz",
    donorEmail: "pedro.cruz@email.com",
    barangay: "San Juan",
    category: "food",
    itemDescription: "Canned goods assorted",
    quantity: 50,
    unit: "cans",
    referenceCode: "DON-AB3XY",
    status: "offered",
    dropOffPoint: "",
    scheduledWindow: "",
    actionLog: [],
    createdAt: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
  },
  {
    _id: "don002",
    donorName: "Carla Mendoza",
    donorEmail: "carla.mendoza@email.com",
    barangay: "San Luis",
    category: "clothing",
    itemDescription: "Used clothing — children sizes",
    quantity: 30,
    unit: "pcs",
    referenceCode: "DON-QR7WZ",
    status: "scheduled",
    dropOffPoint: "Barangay San Luis Hall",
    scheduledWindow: "Sat, May 10 — 9am to 12pm",
    actionLog: [
      { action: "scheduled", by: "Admin Rafael", note: "", at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    _id: "don003",
    donorName: "Jose Bautista",
    donorEmail: "jose.bautista@email.com",
    barangay: "Inarawan",
    category: "water",
    itemDescription: "Mineral water 1.5L",
    quantity: 100,
    unit: "bottles",
    referenceCode: "DON-KP4NM",
    status: "received",
    dropOffPoint: "CDRRMO Office, Antipolo City Hall",
    scheduledWindow: "Fri, May 9 — 1pm to 5pm",
    actionLog: [
      { action: "scheduled", by: "Admin Rafael", note: "", at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString() },
      { action: "received", by: "Admin Rafael", note: "All 100 bottles received in good condition", at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    _id: "don004",
    donorName: "Elena Villanueva",
    donorEmail: "elena.villanueva@email.com",
    barangay: "Dalig",
    category: "other",
    itemDescription: "Sleeping mats",
    quantity: 10,
    unit: "pcs",
    referenceCode: "DON-HT2VB",
    status: "cancelled",
    dropOffPoint: "",
    scheduledWindow: "",
    actionLog: [
      { action: "cancelled", by: "Admin Rafael", note: "Donor could not make it to drop-off", at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString() },
    ],
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
  },
];
